language: c++
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

# env:
#     - PLATFORMIO_CI_SRC=arduino_bootstrapper
#     - PLATFORMIO_CI_SRC=arduino_bootstrapper/core
#     - PLATFORMIO_CI_SRC=arduino_bootstrapper/core/src
#     - PLATFORMIO_CI_SRC=arduino_bootstrapper/core/include

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - sudo platformio run