language: c++
python:
    - "3.7"

sudo: false

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=/prova 

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - pwd
    # - cd /home/travis/build/sblantipodi/pc_ambilight/ ;
    - ls;
    - platformio ci --project-conf=/home/travis/build/sblantipodi/pc_ambilight/platformio.ini 
    # - sudo platformio run -c /home/travis/build/sblantipodi/pc_ambilight/platformio.ini 