language: c++
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino_bootstrapper

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - platformio ci $PLATFORMIO_CI_EXTRA_ARGS
    - sudo platformio run