language: c++
python:
    - "3.7"

sudo: false

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino_bootstrapper/core/src

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - pwd
    - sudo platformio run