language: python
python:
    - "2.7"

sudo: false

cache:
    directories:
        - "~/.platformio"

env: 
    - PLATFORMIO_CI_SRC=/home/travis/build/sblantipodi/pc_ambilight 

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - pwd
    - sudo platformio --version
    - cd /home/travis/build/sblantipodi/pc_ambilight/;
    # - rm -rf /home/travis/build/sblantipodi/pc_ambilight/arduino_bootstrapper/src/ChangeName.cpp
    # - rm -rf /home/travis/build/sblantipodi/pc_ambilight/arduino_bootstrapper/src/Configuration.cpp
    # - ls;
    - sudo platformio ci --project-conf=/home/travis/build/sblantipodi/pc_ambilight/platformio.ini --lib="." --lib="/home/travis/build/sblantipodi/pc_ambilight/arduino_bootstrapper"
    # - sudo platformio run -c /home/travis/build/sblantipodi/pc_ambilight/platformio.ini 
    # - sudo platformio run -e ambilight