language: c++
python:
    - "3.7"

sudo: false

cache:
    directories:
        - "~/.platformio"

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - pwd
    # - platformio ci --project-conf=/home/travis/build/sblantipodi/pc_ambilight/platformio.ini --lib="arduino_bootstrapper"
    - sudo platformio run