language: c++
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - sudo platformio run