name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version        
    - name: Install submodules
        run: |        
        pwd
        git submodule update --init
    - name: Run PlatformIO
      run: platformio run -e github_actions_ci
