name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        pwd
        git submodule update --init
        ls
        sed -i 's,^arduino_bootstrapper =.*$,arduino_bootstrapper = /home/runner/work/pc_ambilight/pc_ambilight/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
    - name: Run PlatformIO
      run: platformio run -e ambilight
